# Generated by Django 5.2.18 on 2026-10-08 14:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='e.g. Cooked Rice & Curry, Fresh Apples, Bread Rolls', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Preparation details, ingredients, or dietary info', null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Total initial quantity', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(help_text='Units: portions, kg, boxes, packets, meals, litres', max_length=50)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Exact expiry deadline')),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('expired', 'Expired'), ('blocked', 'Blocked')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.donor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.location')),
            ],
            options={
                'verbose_name': 'Food Listing',
                'verbose_name_plural': 'Food Listings',
                'ordering': ['expires_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpiryTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('urgency_level', models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('expired', 'Expired')], default='safe', max_length=20)),
                ('alert_sent', models.BooleanField(default=False, help_text='Prevents duplicate urgent or expiry notifications')),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_tracker', to='listings.foodlisting')),
            ],
            options={
                'verbose_name': 'Expiry Tracker',
                'verbose_name_plural': 'Expiry Trackers',
            },
        ),
        migrations.CreateModel(
            name='FoodSafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=20)),
                ('safe_until', models.DateTimeField(blank=True, null=True)),
                ('is_safe', models.BooleanField(default=True, help_text='Whether this listing passed platform safety screening')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_check', to='listings.foodlisting')),
            ],
            options={
                'verbose_name': 'Food Safety Check',
                'verbose_name_plural': 'Food Safety Checks',
            },
        ),
    ]
