# Generated by Django 5.2.18 on 2026-10-08 14:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_quantity', models.DecimalField(decimal_places=2, help_text='Quantity reserved by recipient', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_deadline', models.DateTimeField(help_text='Time window by which food must be picked up')),
                ('pickup_code', models.CharField(db_index=True, help_text='Unique 8-character verification token', max_length=8, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='listings.foodlisting')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='accounts.recipient')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-claimed_at'],
            },
        ),
    ]
