# Generated by Django 5.2.18 on 2026-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Street address or building details', max_length=255)),
                ('area', models.CharField(db_index=True, help_text='Neighborhood or area name', max_length=100)),
                ('city', models.CharField(db_index=True, help_text='City name', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal / ZIP code', max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'indexes': [models.Index(fields=['area'], name='loc_area_idx'), models.Index(fields=['city'], name='loc_city_idx')],
                'constraints': [models.UniqueConstraint(fields=('address', 'area', 'city', 'postal_code'), name='unique_location_address')],
            },
        ),
    ]
